

SELECT DISTINCT DEPOSITOR.CUSTOMER_NAME FROM DEPOSITOR, BORROWER
WHERE DEPOSITOR.CUSTOMER_NAME=BORROWER.CUSTOMER_NAME;

SELECT CUSTOMER_NAME FROM DEPOSITOR
INTERSECT 
SELECT CUSTOMER_NAME FROM BORROWER;

SELECT DISTINCT CUSTOMER.CUSTOMER_NAME,CUSTOMER_CITY,CUSTOMER_STREET
FROM CUSTOMER, DEPOSITOR,BORROWER 
WHERE CUSTOMER.CUSTOMER_NAME= DEPOSITOR.CUSTOMER_NAME OR
CUSTOMER.CUSTOMER_NAME=BORROWER.CUSTOMER_NAME;


SELECT CUSTOMER.CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY FROM CUSTOMER,BORROWER
WHERE CUSTOMER.CUSTOMER_NAME = BORROWER.CUSTOMER_NAME
UNION
SELECT CUSTOMER.CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY FROM CUSTOMER,DEPOSITOR
WHERE CUSTOMER.CUSTOMER_NAME = DEPOSITOR.CUSTOMER_NAME;

SELECT DISTINCT CUSTOMER.CUSTOMER_NAME, CUSTOMER_CITY
FROM CUSTOMER,BORROWER,DEPOSITOR
WHERE CUSTOMER.CUSTOMER_NAME = BORROWER.CUSTOMER_NAME AND
CUSTOMER.CUSTOMER_NAME NOT IN (
SELECT DISTINCT CUSTOMER.CUSTOMER_NAME 
FROM CUSTOMER,BORROWER,DEPOSITOR
WHERE CUSTOMER.CUSTOMER_NAME = BORROWER.CUSTOMER_NAME AND CUSTOMER.CUSTOMER_NAME = DEPOSITOR.CUSTOMER_NAME);

SELECT DISTINCT CUSTOMER.CUSTOMER_NAME, CUSTOMER_CITY
FROM CUSTOMER, BORROWER
WHERE CUSTOMER.CUSTOMER_NAME = BORROWER.CUSTOMER_NAME
MINUS 
SELECT DISTINCT CUSTOMER.CUSTOMER_NAME, CUSTOMER_CITY
FROM CUSTOMER, DEPOSITOR
WHERE CUSTOMER.CUSTOMER_NAME = DEPOSITOR.CUSTOMER_NAME;

SELECT SUM(ASSETS) FROM  BRANCH;


SELECT BRANCH_CITY,COUNT(ACCOUNT_NUMBER) FROM BRANCH, ACCOUNT WHERE ACCOUNT.BRANCH_NAME=BRANCH.BRANCH_NAME
GROUP BY BRANCH_CITY;