DROP TABLE CITIZEN CASCADE CONSTRAINTS; 
DROP TABLE DIVISION CASCADE CONSTRAINTS; 
DROP TABLE DISTRICT CASCADE CONSTRAINTS; 
DROP TABLE HOSPITAL CASCADE CONSTRAINTS; 
DROP TABLE ADMISSION CASCADE CONSTRAINTS; 
DROP TABLE DRIVING_LICENSE CASCADE CONSTRAINTS; 
DROP TABLE CENTRAL_SYSTEM CASCADE CONSTRAINTS; 



CREATE TABLE CITIZEN
(
    NID INT PRIMARY KEY, 
    NAME VARCHAR2(50), 
    DATE_OF_BIRTH DATE, 
    OCCUPATION VARCHAR2(20), 
    BLOOD_GROUP VARCHAR2(3), 
    FOREING KEY DIVISION_NAME  REFERENCES DIVISION(NAME) ,
    FOREING KEY DISTRICT_NAME REFERENCES DISTRICT(NAME) ,
    FOREING KEY DRIVER_ID REFERENCES DRIVING_LICENSE(LICENSE_ID)
);
CREATE TABLE DIVISION
(
    NAME VARCHAR2(20) PRIMARY KEY, 
    SIZE NUMBER , 
    DESCRIPTION VARCHAR2(200), 
    NUMBER_OF_DISTRICTS INT 

);
CREATE TABLE DISTRICT
(
    NAME VARCHAR(20) PRIMARY KEY , 
    SIZE NUMBER, 
    DESCRIPTION VARCHAR2(200),
    FOREING KEY DIVISION_SITUATED_IN REFERENCES DIVISION(NAME)
);
CREATE TABLE HOSPITAL
(
    HOSPITAL_REG_ID INT PRIMARY KEY , 
    NAME VARCHAR2(100),
    CONTACT_NUMBER NUMBER
);
CREATE TABLE ADMISSION
(
    ADMISSION_ID INT PRIMARY KEY , 
    DATE_OF_ADMISSION DATE, 
    DESCRIPTION_OF_PATIENT VARCHAR2(200), 
    RELEASE_DATE DATE,
    FOREING KEY NID REFERENCES CITIZEN(NID) ,
    FOREING KEY HOSPITAL_ID REFERENCES HOSPITAL(HOSPITAL_REG_ID)

);
CREATE TABLE DRIVING_LICENSE
(
    LICENSE_ID INT PRIMARY KEY,
    LICENSE_TYPE VARCHAR2(10), 
    ISSUE_DATE DATE, 
    EXPIRY_DATE DATE
);
CREATE TABLE CENTRAL_SYSTEM
(
    OCCURENCE_ID INT PRIMARY KEY , 
    DATE_TIME_OF_ACCIDENT DATE, 
    LOCATION VARCHAR2 (200), 
    NUMBER_OF_DEATHS INT , 
    FOREING KEY LICENSE_ID REFERENCES DRIVING_LICENSE(LICENSE_ID)
);


-- QUERIES


 SELECT NAME , NUMBER_OF_DISTRICTS
 FROM
 (
    SELECT NAME,COUNT(NAME.DISTRICT) AS NUMBER_OF_DISTRICTS
    FROM DISTRICT 
    JOIN DISTRICT 
    ON DIVISION.NAME=DISTRICT.DIVISION_SITUATED_IN
    GROUP BY NAME

 )
 --OR 
SELECT DIVISION.NAME,COUNT(DISTRICT.NAME) AS TOTAL_NUM_DISTRICTS
FROM DIVISION,DISTRICT
WHERE (SELECT DISTRICT.NAME FROM DISTRICT,DIVISION WHERE DIVISION.NAME = DISTRICT.DIVISION_SITUATED_IN);

 
 ORDER BY NAME , NUMBER_OF_DISTRICTS DESC ;

 SELECT NAME
 FROM
 (
    SELECT COUNT(NID) AS POPULATION 
    WHERE POPULATION>=20000
    FROM CITIZEN
    JOIN DISTRICT
    ON CITIZEN.DISTRICT_NAME=DISTRICT.NAME
    GROUP BY DISTRICT_NAME

 )
ORDER BY NAME,POPULATION DESC; 

-- OR
SELECT DISTRICT.NAME
FROM CITIZEN,DISTRICT
WHERE (SELECT COUNT(CITIZEN.NID) FROM CITIZEN,DISTRICT WHERE CITIZEN.DISTRICT=DISTRICT.NAME)>=20000
 


SELECT COUNT(OCCURENCE_ID)
FROM CENTRAL_SYSTEM,DRIVING_LICENSE,CITIZEN
WHERE (SELECT NID FROM CITIZEN,DRIVING_LICENSE,CENTRAL_SYSTEM
WHERE CITIZEN.LICENSE_ID = DRIVING_LICENSE.LICENSE_ID,DRIVING_LICENSE.LICENSE_ID=CENTRAL_SYSTEM.LICENSE_ID)=210

SELECT ROWNUM AS HOSPITAL_RANK , HOSPITAL.HOSPITAL_ID
FROM(SELECT DISTINCT(HOSPITAL.HOSPITAL_ID),COUNT(ADMISSION_ID.NID)TOTAL_ADMIT
FROM HOSPITAL, ADMISSION
WHERE HOSPITAL.HOSPITAL_ID=ADMISSION.HOSPITAL_ID
GROUP BY HOSPITAL_ID
ORDER BY TOTAL_ADMIT DESC)
WHERE ROWNUM<=3;

