DROP TABLE BRANCH CASCADE CONSTRAINTS; 
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS; 
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE HOUSE CASCADE CONSTRAINTS;
DROP TABLE OWNER CASCADE CONSTRAINTS; 
DROP TABLE VISITS CASCADE CONSTRAINTS;


CREATE TABLE BRANCH 
(
    BRANCH_ID INT PRIMARY KEY, 
    STREET VARCHAR2(20),
    CITY VARCHAR(20),
    POST_CODE VARCHAR(4)
);

CREATE TABLE EMPLOYEE 
(
    EMPLOYEE_ID INT PRIMARY KEY, 
    FIRST_NAME VARCHAR(20), 
    LAST_NAME VARCHAR(20), 
    GENDER VARCHAR(20),  
    DATE_OF_BIRTH DATE, 
    POSITION VARCHAR2(20),
    SALARY NUMBER(10), 
    BRANCH REFERENCES BRANCH NOT NULL 
    
    
);
CREATE TABLE CLIENT 
(
    CLIENT_ID INT PRIMARY KEY, 
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    TELEPHONE_NO NUMBER(20),
    EMAIL VARCHAR2(20),
    PREFERED_TYPE VARCHAR2(20),
    MAX_RENT INT , 
    STUFF REFERENCES EMPLOYEE NOT NULL,
    BRANCH REFERENCES BRANCH NOT NULL
);
CREATE TABLE HOUSE 
(
    HOUSE_ID INT PRIMARY KEY, 
    STREET VARCHAR2(20), 
    CITY VARCHAR2(20),
    POST_CODE VARCHAR2(20), 
    NO_OF_ROOMS VARCHAR2(20), 
    RENT NUMBER, 
    STAFF REFERENCES EMPLOYEE NOT NULL
)

CREATE TABLE OWNER 
(
    OWNER ID INT PRIMARY KEY, 
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(20),
    TELEPHONE_NO NUMBER(20),
    EMAIL VARCHAR2(20), 
    PASSWORD VARCHAR2(20).
    HOUSE_ID REFERENCES HOUSE NOT NULL
);

CREATE TABLE VISITS 
(
    CLIENT_ID REFERENCES CLIENT NOT NULL, 
    HOUSE_ID REFERENCES HOUSE NOT NULL, 
    DATE_OF_VISIT DATE, 
    COMMENTS VARCHAR2, 
    CLIENT_ID,HOUSE_ID PRIMARY KEY
);