CREATE TABLE ACCOUNT(
    ACCOUNT_NO CHAR(5),
    BALANCE NUMBER NOT NULL
);
ALTER TABLE ACCOUNT ADD PRIMARY KEY (ACCOUNT_NO);
CREATE TABLE CUSTOMER(
    CUSTOMER_NO CHAR(5),
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_CITY VARCHAR2(10)
);
ALTER TABLE CUSTOMER ADD PRIMARY KEY (CUSTOMER_NO);


CREATE TABLE DEPOSITOR AS SELECT ACCOUNT_NO FROM ACCOUNT;
ALTER TABLE DEPOSITOR ADD CUSTOMER_NO CHAR(5);
ALTER TABLE DEPOSITOR ADD PRIMARY KEY (ACCOUNT_NO, CUSTOMER_NO);

ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH DATE;

ALTER TABLE ACCOUNT MODIFY BALANCE NUMBER(12,2);

ALTER TABLE DEPOSITOR RENAME COLUMN ACCOUNT_NO TO A_NO;

ALTER TABLE DEPOSITOR RENAME COLUMN CUSTOMER_NO TO C_NO;
ALTER TABLE DEPOSITOR RENAME TO DEPOSITOR_INFO;

ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT FOREIGN KEY(A_NO)
REFERENCES ACCOUNT(ACCOUNT_NO);

ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER FOREIGN KEY(C_NO)
REFERENCES CUSTOMER(CUSTOMER_NO);


SELECT ACCOUNT_NO FROM ACCOUNT WHERE BALANCE>1000000;

SELECT ACCOUNT_NO FROM ACCOUNT WHERE BALANCE >100000;
SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_CITY = 'Dhaka';
SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_NAME LIKE 'A%';
SELECT DISTINCT(A_NO) FROM DEPOSITOR_INFO;
SELECT * FROM ACCOUNT, DEPOSITOR_INFO;
SELECT * FROM CUSTOMER NATURAL JOIN DEPOSITOR_INFO;

SELECT CUSTOMER_NAME, CUSTOMER_CITY FROM CUSTOMER, ACCOUNT, DEPOSITOR_INFO
WHERE CUSTOMER.CUSTOMER_NO = DEPOSITOR_INFO.C_NO AND ACCOUNT.ACCOUNT_NO = DEPOSITOR_INFO.A_NO;

SELECT CUSTOMER_NAME, CUSTOMER_CITY FROM ACCOUNT,
DEPOSITOR_INFO, CUSTOMER
WHERE ACCOUNT.ACCOUNT_NO=DEPOSITOR_INFO.A_NO AND 
CUSTOMER.CUSTOMER_NO=DEPOSITOR_INFO.C_NO AND BALANCE >1000;

SELECT ACCOUNT_NO,BALANCE FROM ACCOUNT, DEPOSITOR_INFO, ACCOUNT WHERE
ACCOUNT.ACCOUNT_NO=DEPOSITOR_INFO.A_NO AND 
CUSTOMER.CUSTOMER_NO=DEPOSITOR_INFO.C_NO AND BALANCE > 5000 AND 
BALANCE <10000 AND CUSTOMER_CITY = 'Khulna';